# permissions for end users to edit charts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chart-editor-role
rules:
- apiGroups:
  - helm.snorwin.io
  resources:
  - charts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - helm.snorwin.io
  resources:
  - charts/status
  verbs:
  - get
