
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - helm.snorwin.io
  resources:
  - releases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - helm.snorwin.io
  resources:
  - releases/finalizers
  verbs:
  - update
- apiGroups:
  - helm.snorwin.io
  resources:
  - releases/status
  verbs:
  - get
  - patch
  - update
