name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: make all

    - uses: actions/upload-artifact@v2
      with:
        name: manager
        path: bin/manager
        if-no-files-found: error

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1

      - uses: actions/download-artifact@v2
        with:
          name: manager

      - name: Login to quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAYIO_USER }}
          password: ${{ secrets.QUAYIO_TOKEN }}

      - run: cp build/Dockerfile .

      - name: Build and deploy image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
          tags: quay.io/snorwin/helm-operator:latest
